# Generated by Django 3.2.19 on 2023-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eveitemtax',
            name='amarr_buy_percentage',
        ),
        migrations.RemoveField(
            model_name='eveitemtax',
            name='effective_rate',
        ),
        migrations.RemoveField(
            model_name='eveitemtax',
            name='jita_sell_percentage',
        ),
        migrations.AlterField(
            model_name='eveitemtax',
            name='flat_cost',
            field=models.IntegerField(default=0),
        ),
    ]
