# Generated by Django 3.2.19 on 2023-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0002_auto_20230803_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveitemtax',
            name='group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
